version: '3'
services:
    apache:
        image: andrerodrigue5/apache2-php7.3.14:1.0.0
        container_name: apache-gameroom
        ports:
            - "8100:80"
            - "4100:443"
            - "5200:5200"
        volumes:
            - .:/var/www/html/
        networks:
            - docker-rede
        depends_on:
            - "mariadb"
        restart: always
    mariadb:
        image: mariadb:10.1.26
        container_name: mariadb-gameroom
        ports:
            - "3100:3306"
        environment:
            MYSQL_DATABASE: gameroom
            MYSQL_ROOT_PASSWORD: 123456
        networks:
            - docker-rede
        volumes:
            - ./database/mysql/:/var/lib/mysql
        restart: always
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        container_name: phpmyadmin-gameroom
        ports:
            - "1100:80"
        environment:
            PMA_HOST: mariadb-gameroom
            PMA_PORT: 3306
        networks:
            - docker-rede
        depends_on:
            - "apache"
        restart: always
networks:
    docker-rede:
        driver: bridge
